lang: ast: Remove redundant nil check
purpleidea/mgmt pull request #731
Opened 2024-01-26 13:55 UTC by Juneezee

From the Go specification [^1]:

> "1. ... For a nil slice, the number of iterations is 0."

Therefore, an additional nil check for around the loop is unnecessary.

[^1]: https://go.dev/ref/spec#For_range

/cc @purpleidea for review

2024-01-26 13:57 UTC, Juneezee reviewed
Small tip: Hide whitespace changes to make the diff easier to read

![image](https://github.com/purpleidea/mgmt/assets/20135478/a5284a33-fcf0-45e6-a454-4cfcaa83c230)

---

![image](https://github.com/purpleidea/mgmt/assets/20135478/e45f1e72-a919-4aac-a61c-85b63f0eef74)

2024-01-27 09:25 UTC, Juneezee commented
@purpleidea I apologize for the nil pointer panic introduced in the first commit. I have pushed a fix for the panic. Please approve the CI runs again :bowing_man: .

CI runs in my fork are now green https://github.com/Juneezee/mgmt/actions/runs/7677576810

2024-01-28 18:28 UTC, purpleidea commented
@Juneezee Thanks for the patch-- just a quick question or two if you don't mind:

1) What tool did you use to find these changes?
2) Are you interested in making some bigger mgmt patches?
3) Thanks! 
![image](https://github.com/purpleidea/mgmt/assets/135091/c427d27e-0619-41ab-8ab1-94fb5abdb600)

2024-01-28 18:57 UTC, Juneezee commented
> just a quick question or two if you don't mind:

@purpleidea Yup, I don't mind :smile: 

> 1. What tool did you use to find these changes?

GitHub search. I was searching for "abstract syntax tree" to find some code for learning purposes. This repository is one of the top results on the first page.

This was the search query that I used: `"abstract syntax tree" lang:Go -repo:golang/go`

![image](https://github.com/purpleidea/mgmt/assets/20135478/8696019a-e0c7-4f3e-8664-9cd29eb3e5ee)

> 2. Are you interested in making some bigger mgmt patches?

Yes! Absolutely!

> 3. Thanks!
>    ![image](https://private-user-images.githubusercontent.com/135091/300285177-c427d27e-0619-41ab-8ab1-94fb5abdb600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NjgxOTEsIm5iZiI6MTcwNjQ2Nzg5MSwicGF0aCI6Ii8xMzUwOTEvMzAwMjg1MTc3LWM0MjdkMjdlLTA2MTktNDFhYi04YWIxLTk0ZmI1YWJkYjYwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxODUxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDZiMzNiNTY4N2MxYTcyMjE3MDMyNmJhZTFlNDI4MWI2MDcwNzk4NDY0YzBhMTU2YmRiMGYyMjk0OTVhYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rIX803hmMA3pIdegqtuhXR3bepbaMxHSyj5iWKo267Y)

1997, my birth year :smile:

2024-01-28 19:03 UTC, purpleidea commented
> What tool did you use to find these changes?

Thanks for the info-- sorry what I mean was, what linting tool did you use to find the specific code changes to make, or did you read through the whole file and decide on them manually?

>> Are you interested in making some bigger mgmt patches?
> Yes! Absolutely!

Okay great! Want to give me a quick summary of your strengths and weaknesses in golang, if you're comfortable with golang concurrency, and what you'd like to work on. Eg: parser stuff, a resource, a function, concurrency bugs etc...

I can help you choose and mentor you on your patches. Cheers!

2024-01-28 19:34 UTC, Juneezee commented
> Thanks for the info-- sorry what I mean was, what linting tool did you use to find the specific code changes to make, or did you read through the whole file and decide on them manually?

I did skim through the whole file. I use GoLand and I noticed the slice declaration warning, which is just 1 line above my change.

![image](https://github.com/purpleidea/mgmt/assets/20135478/bc0dc225-1c86-4325-937c-19c0f6aebd48)


> Okay great! Want to give me a quick summary of your strengths and weaknesses in golang, if you're comfortable with golang concurrency, and what you'd like to work on. Eg: parser stuff, a resource, a function, concurrency bugs etc...
> 
> I can help you choose and mentor you on your patches. Cheers!

I would say I'm pretty confident in normal day-to-day Go programming, and I'm comfortable with Go concurrency too.

However, I lack experience with project architecture and engineering practices (stuff like that). If there are issues or feature requests that you think are beginner-friendly, feel free to assign them to me and I am happy to work on it :smile:

2024-01-28 19:49 UTC, purpleidea commented
> slice declaration warning

Interesting, I didn't consider this a bad practice. I'll look into it more.

> feel free to assign them to me and I am happy to work on it 😄

Okay, since you mentioned AST's and compilers, I wrote up an issue over here... https://github.com/purpleidea/mgmt/issues/732 If you're interested in that one, LMK and comment over there that you're working on it. If you want something different, please LMK.

2024-02-08 16:48 UTC, frebib approved these changes

2024-02-08 20:24 UTC, purpleidea requested changes
Looks good, just the one change throughout as mentioned and please rebase into a single commit against master. Thank you!

2024-02-08 20:24 UTC, purpleidea commented on lang/ast/structs.go
> +	args := make([]interfaces.Expr, 0, len(obj.Args))
Please leave this definition site as it was, the compiler should be able to optimize this for us. If not, it's okay, it's not an area we need to optimize at this time. It's much harder (at least for me) to read.

2024-02-08 20:33 UTC, purpleidea commented
LGTM, let's see what CI says... Thanks!

2024-02-08 21:11 UTC, merged

2024-02-08 21:18 UTC, Juneezee commented
> Merged, thank you!
> 
> What's next?

I'll be looking into https://github.com/purpleidea/mgmt/issues/732, and I hope I can solve it